# Use Node.js v22 slim image
FROM node:23-slim

# Set working directory
WORKDIR /frontend

# Copy only package files to leverage caching
COPY package*.json ./

# Install dependencies (adjust as needed for dev/prod)
# RUN npm install --omit=dev

# Copy the rest of the application
COPY . .
