version: '3.8'

services:
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "build"]
    volumes:
      - frontend-build:/app/dist
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - frontend-build:/app/frontend  # Mount built frontend here
    depends_on:
      - frontend
      - ai
    networks:
      - app-network

volumes:
  frontend-build:

networks:
  app-network:
    driver: bridge
