version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - ai
    networks:
      - app-network

  ai:
    build: ./ai
    ports:
      - "8000:8000"
    volumes:
      - ./ai:/app
    environment:
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
