version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - ai

  ai:
    build: ./ai
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
      - ai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
