# use python:3.12-slim image
FROM python:3.13-slim

# Set working directory
WORKDIR /services

# Copy requirements first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the project
COPY . .