services:
  ai-server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
    stdin_open: true   # Enables interactive mode (for exec -it)
    tty: true          # Keeps terminal session open
